// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectName.DomainName.Infra.Server.Data.Context;

namespace ProjectName.DomainName.Infra.Server.Data.Migrations
{
    [DbContext(typeof(DomainName_Context))]
    [Migration("20181101153113_DomainName_v1.0")]
    partial class DomainName_v10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectName.DomainName.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Street")
                        .HasColumnType("varchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ProjectName.DomainName.Domain.Models.Address", b =>
                {
                    b.OwnsOne("ProjectName.DomainName.Domain.ValueObjects.City", "City", b1 =>
                        {
                            b1.Property<Guid?>("AddressId");

                            b1.Property<string>("Name")
                                .HasColumnName("City")
                                .HasColumnType("varchar(50)");

                            b1.ToTable("Addresses");

                            b1.HasOne("ProjectName.DomainName.Domain.Models.Address")
                                .WithOne("City")
                                .HasForeignKey("ProjectName.DomainName.Domain.ValueObjects.City", "AddressId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
